### ISSUE TITLE
Failing `mix igniter.new app_name --install ash --with phx.new`

### ISSUE THREAD

**Issue by coenbakker** [ash-project/igniter#100]
Running `mix igniter.new pinecone --install ash --with phx.new` results in the following exception.

```
** (ArgumentError) construction of binary failed: segment 1 of type 'binary': expected a binary but got: #Igniter<rewrite: #Rewrite<2 source(s)>>
    (igniter 0.3.58) lib/igniter/util/io.ex:6: Igniter.Util.IO.yes?/1
    (igniter 0.3.58) lib/igniter.ex:806: Igniter.do_or_dry_run/2
    (igniter 0.3.58) lib/igniter/util/install.ex:140: Igniter.Util.Install.run_installers/5
    (igniter 0.3.58) lib/igniter/util/install.ex:103: Igniter.Util.Install.install/4
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    lib/mix/tasks/igniter.new.ex:178: Mix.Tasks.Igniter.New.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
```

To Reproduce:
- run `mix igniter.new pinecone --install ash --with phx.new`
- Continue with either "Yes" or "No" when prompted `Fetch and install dependencies? [Yn]`
- Continue with "Yes" when prompted with:

   ```
               ...|
    34 34    |  defp deps do
    35 35    |    [
         36 + |      {:ash, "~> 3.0"},
    36 37    |      {:igniter, "~> 0.3"},
    37 38    |      {:phoenix, "~> 1.7.14"},
              ...|
    
    These dependencies should be installed before continuing. Modify mix.exs and install? [y/n]
    ```

After that last step the following output is visible in your CLI.

```
running mix deps.get
    warning: redefining module Pinecone.MixProject (current version defined in memory)
    │
  1 │ defmodule Pinecone.MixProject do
    │ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ mix.exs:1: Pinecone.MixProject (module)

==> stream_data
Compiling 3 files (.ex)
Generated stream_data app
==> libgraph
Compiling 15 files (.ex)
Generated libgraph app
===> Analyzing applications...
===> Compiling telemetry
===> Analyzing applications...
===> Compiling telemetry_poller
==> splode
Compiling 5 files (.ex)
Generated splode app
==> ets
Compiling 7 files (.ex)
Generated ets app
==> iterex
Compiling 48 files (.ex)
Generated iterex app
==> spark
Compiling 36 files (.ex)
Generated spark app
==> reactor
Compiling 86 files (.ex)
Generated reactor app
==> owl
Compiling 19 files (.ex)
Generated owl app
==> ash
Compiling 499 files (.ex)
Generated ash app
==> phoenix_live_view
Compiling 39 files (.ex)
==> pinecone

The following installer was found and executed: `ash`:
Update: .formatter.exs

1 1   |[
2   - |  import_deps: [:ecto, :ecto_sql, :phoenix],
  2 + |  import_deps: [:ash, :ecto, :ecto_sql, :phoenix],
3 3   |  subdirectories: ["priv/*/migrations"],
4   - |  plugins: [Phoenix.LiveView.HTMLFormatter],
  4 + |  plugins: [Spark.Formatter, Phoenix.LiveView.HTMLFormatter],
5 5   |  inputs: ["*.{heex,ex,exs}", "{config,lib,test}/**/*.{heex,ex,exs}", "priv/*/seeds.exs"]
6 6   |]
   ...|


Update: config/config.exs

     ...|
 8  8   |import Config
 9  9   |
   10 + |config :ash,
   11 + |  include_embedded_source_by_default?: false,
   12 + |  default_page_type: :keyset,
   13 + |  policies: [no_filter_static_forbidden_reads?: false]
   14 + |
   15 + |config :spark,
   16 + |  formatter: [
   17 + |    remove_parens?: true,
   18 + |    "Ash.Resource": [
   19 + |      section_order: [
   20 + |        :resource,
   21 + |        :code_interface,
   22 + |        :actions,
   23 + |        :policies,
   24 + |        :pub_sub,
   25 + |        :preparations,
   26 + |        :changes,
   27 + |        :validations,
   28 + |        :multitenancy,
   29 + |        :attributes,
   30 + |        :relationships,
   31 + |        :calculations,
   32 + |        :aggregates,
   33 + |        :identities
   34 + |      ]
   35 + |    ],
   36 + |    "Ash.Domain": [section_order: [:resources, :policies, :authorization, :domain, :execution]]
   37 + |  ]
   38 + |
10 39   |config :pinecone,
11 40   |  ecto_repos: [Pinecone.Repo],
     ...|


** (ArgumentError) construction of binary failed: segment 1 of type 'binary': expected a binary but got: #Igniter<rewrite: #Rewrite<2 source(s)>>
    (igniter 0.3.58) lib/igniter/util/io.ex:6: Igniter.Util.IO.yes?/1
    (igniter 0.3.58) lib/igniter.ex:806: Igniter.do_or_dry_run/2
    (igniter 0.3.58) lib/igniter/util/install.ex:140: Igniter.Util.Install.run_installers/5
    (igniter 0.3.58) lib/igniter/util/install.ex:103: Igniter.Util.Install.install/4
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    lib/mix/tasks/igniter.new.ex:178: Mix.Tasks.Igniter.New.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
```

Runtime

- Elixir v1.17.3
- Erlang v27.1.1
- MacOS v15.0.1
- igniter_new v0.4.2

**Comment by zachdaniel** [comment]
Thank you for letting me know! This is fixed in the latest release 🙇
