### ISSUE TITLE
Spooky warnings and failure on nerves.new

### ISSUE THREAD

**Issue by lawik** [ash-project/igniter#82]
**Describe the bug**

I ran the `igniter.new` task v0.3.5 with `nerves.new`.

I got a lot of warnings and did not get the `nerves_hub_link` dependency I tried to get.

```
larswikman@Sliver projects % mix igniter.new --with nerves.new --install nerves_hub_link codebeam
* creating codebeam/config/config.exs
* creating codebeam/config/host.exs
* creating codebeam/config/target.exs
* creating codebeam/lib/codebeam.ex
* creating codebeam/lib/codebeam/application.ex
* creating codebeam/test/test_helper.exs
* creating codebeam/test/codebeam_test.exs
* creating codebeam/rel/vm.args.eex
* creating codebeam/rootfs_overlay/etc/iex.exs
* creating codebeam/.gitignore
* creating codebeam/.formatter.exs
* creating codebeam/mix.exs
* creating codebeam/README.md

Fetch and install dependencies? [Yn] y
* running mix deps.get
* running mix format
Your Nerves project was created successfully.

You should now pick a target. See https://hexdocs.pm/nerves/supported-targets.html
for supported targets. If your target is on the list, set `MIX_TARGET`
to its tag name:

For example, for the Raspberry Pi 3 you can either
  $ export MIX_TARGET=rpi3
Or prefix `mix` commands like the following:
  $ MIX_TARGET=rpi3 mix firmware

If you will be using a custom system, update the `mix.exs`
dependencies to point to desired system's package.

Now download the dependencies and build a firmware archive:
  $ cd codebeam
  $ mix deps.get
  $ mix firmware

If your target boots up using an SDCard (like the Raspberry Pi 3),
then insert an SDCard into a reader on your computer and run:
  $ mix burn

Plug the SDCard into the target and power it up. See target documentation
above for more information and other targets.

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 178 │       case Macro.Env.define_alias(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ lib/spitfire/env.ex:178:22: Spitfire.Env.expand/3
     └─ lib/spitfire/env.ex:481:28: Spitfire.Env.alias_defmodule/3

     warning: Macro.Env.define_import/4 is undefined or private
     │
 209 │            {:ok, env} <- Macro.Env.define_import(env, meta, arg, [trace: false] ++ opts) do
     │                                    ~
     │
     └─ lib/spitfire/env.ex:209:36: Spitfire.Env.expand/3

     warning: Macro.Env.define_require/4 is undefined or private
     │
 193 │       case Macro.Env.define_require(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ lib/spitfire/env.ex:193:22: Spitfire.Env.expand/3

     warning: Macro.Env.expand_alias/4 is undefined or private
     │
 137 │     case Macro.Env.expand_alias(env, meta, list, trace: false) do
     │                    ~
     │
     └─ lib/spitfire/env.ex:137:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_import/5 is undefined or private
     │
 308 │     case Macro.Env.expand_import(env, meta, fun, arity,
     │                    ~
     │
     └─ lib/spitfire/env.ex:308:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_require/6 is undefined or private
     │
 274 │       case Macro.Env.expand_require(env, meta, module, fun, arity,
     │                      ~
     │
     └─ lib/spitfire/env.ex:274:22: Spitfire.Env.expand/3

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 178 │       case Macro.Env.define_alias(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:178:22: Spitfire.Env.expand/3

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 481 │     {:ok, env} = Macro.Env.define_alias(env, meta, module, as: alias, trace: false)
     │                            ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:481:28: Spitfire.Env.alias_defmodule/3

     warning: Macro.Env.define_import/4 is undefined or private
     │
 209 │            {:ok, env} <- Macro.Env.define_import(env, meta, arg, [trace: false] ++ opts) do
     │                                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:209:36: Spitfire.Env.expand/3

     warning: Macro.Env.define_require/4 is undefined or private
     │
 193 │       case Macro.Env.define_require(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:193:22: Spitfire.Env.expand/3

     warning: Macro.Env.expand_alias/4 is undefined or private
     │
 137 │     case Macro.Env.expand_alias(env, meta, list, trace: false) do
     │                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:137:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_import/5 is undefined or private
     │
 308 │     case Macro.Env.expand_import(env, meta, fun, arity,
     │                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:308:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_require/6 is undefined or private
     │
 274 │       case Macro.Env.expand_require(env, meta, module, fun, arity,
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:274:22: Spitfire.Env.expand/3

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 178 │       case Macro.Env.define_alias(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:178:22: Spitfire.Env.expand/3

     warning: Macro.Env.define_alias/4 is undefined or private
     │
 481 │     {:ok, env} = Macro.Env.define_alias(env, meta, module, as: alias, trace: false)
     │                            ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:481:28: Spitfire.Env.alias_defmodule/3

     warning: Macro.Env.define_import/4 is undefined or private
     │
 209 │            {:ok, env} <- Macro.Env.define_import(env, meta, arg, [trace: false] ++ opts) do
     │                                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:209:36: Spitfire.Env.expand/3

     warning: Macro.Env.define_require/4 is undefined or private
     │
 193 │       case Macro.Env.define_require(env, meta, arg, [trace: false] ++ opts) do
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:193:22: Spitfire.Env.expand/3

     warning: Macro.Env.expand_alias/4 is undefined or private
     │
 137 │     case Macro.Env.expand_alias(env, meta, list, trace: false) do
     │                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:137:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_import/5 is undefined or private
     │
 308 │     case Macro.Env.expand_import(env, meta, fun, arity,
     │                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:308:20: Spitfire.Env.expand/3

     warning: Macro.Env.expand_require/6 is undefined or private
     │
 274 │       case Macro.Env.expand_require(env, meta, module, fun, arity,
     │                      ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:274:22: Spitfire.Env.expand/3

** (TokenMissingError) token missing on config/config.exs:22:3:
    error: missing terminator: end
    │
 21 │ if Mix.target() == :host do
    │                          └ unclosed delimiter
 22 │   
    │   └ missing closing delimiter (expected "end")
    │
    └─ config/config.exs:22:3
    (elixir 1.16.2) lib/code.ex:571: Code.validated_eval_string/3
    (elixir 1.16.2) lib/config.ex:290: Config.__eval__!/3
    (elixir 1.16.2) lib/config/reader.ex:70: Config.Reader.eval!/3
    (igniter 0.3.34) lib/igniter.ex:1086: Igniter.with_evaled_configs/2
    (igniter 0.3.34) lib/igniter.ex:1047: anonymous fn/4 in Igniter.format/2
    (rewrite 0.10.5) lib/rewrite.ex:460: Rewrite.apply_update!/2
    (rewrite 0.10.5) lib/rewrite.ex:561: anonymous fn/3 in Rewrite.map!/2

```

**To Reproduce**

Elixir & Erlang:

```
elixir          1.16.2-otp-26
erlang          26.1.2
```

Install nerves tooling:

```
mix archive.install hex nerves_bootstrap
```

```
mix igniter.new --with nerves.new --install nerves_hub_link codebeam
```

**Expected behavior**

No warnings and the dependency I requested? :)

**Comment by lawik** [comment]
Okay, seems to choke on this config in config/config.exs:

```
if Mix.target() == :host do
  import_config "host.exs"
else
  import_config "target.exs"
end
```

**Comment by zachdaniel** [comment]
These warnings:      

```
warning: Macro.Env.expand_import/5 is undefined or private
     │
 308 │     case Macro.Env.expand_import(env, meta, fun, arity,
     │                    ~
     │
     └─ (spitfire 0.1.3) lib/spitfire/env.ex:308:20: Spitfire.Env.expand/3
```

Can be ignored. Just warnings in dependency compilation, that go away on the latest version of Elixir.


This one:

```
** (TokenMissingError) token missing on config/config.exs:22:3:
    error: missing terminator: end
    │
 21 │ if Mix.target() == :host do
    │                          └ unclosed delimiter
 22 │   
    │   └ missing closing delimiter (expected "end")
    │
    └─ config/config.exs:22:3
    (elixir 1.16.2) lib/code.ex:571: Code.validated_eval_string/3
    (elixir 1.16.2) lib/config.ex:290: Config.__eval__!/3
    (elixir 1.16.2) lib/config/reader.ex:70: Config.Reader.eval!/3
    (igniter 0.3.34) lib/igniter.ex:1086: Igniter.with_evaled_configs/2
    (igniter 0.3.34) lib/igniter.ex:1047: anonymous fn/4 in Igniter.format/2
    (rewrite 0.10.5) lib/rewrite.ex:460: Rewrite.apply_update!/2
    (rewrite 0.10.5) lib/rewrite.ex:561: anonymous fn/3 in Rewrite.map!/2
```

however is the crux of the problem. Yeah, as you've shown, it's somehow generating syntactically incorrect config. Will reproduce in a test.

**Comment by zachdaniel** [comment]
Fixed in 72bd35413efb24bc666e94f6f924db2d3614e4b7

Released in `0.3.35`
