### ISSUE TITLE
which command missing in Windows

### ISSUE THREAD

**Issue by user20230119** [ash-project/igniter#99]
**Describe the bug**
`which` command is missing on Windows.

**To Reproduce**
```
mix igniter.new helpdesk --install ash,ash_postgres --with phx.new --extend postgres --example
* creating helpdesk/lib/helpdesk/application.ex
* creating helpdesk/lib/helpdesk.ex
* creating helpdesk/lib/helpdesk_web/controllers/error_json.ex
* creating helpdesk/lib/helpdesk_web/router.ex
* creating helpdesk/lib/helpdesk_web/telemetry.ex
* creating helpdesk/lib/helpdesk_web.ex
* creating helpdesk/mix.exs
* creating helpdesk/README.md
* creating helpdesk/.formatter.exs
* creating helpdesk/.gitignore
* creating helpdesk/test/support/conn_case.ex
* creating helpdesk/test/test_helper.exs
* creating helpdesk/test/helpdesk_web/controllers/error_json_test.exs
* creating helpdesk/lib/helpdesk/repo.ex
* creating helpdesk/priv/repo/migrations/.formatter.exs
* creating helpdesk/priv/repo/seeds.exs
* creating helpdesk/test/support/data_case.ex
* creating helpdesk/lib/helpdesk_web/controllers/error_html.ex
* creating helpdesk/test/helpdesk_web/controllers/error_html_test.exs
* creating helpdesk/lib/helpdesk_web/components/core_components.ex
* creating helpdesk/lib/helpdesk_web/controllers/page_controller.ex
* creating helpdesk/lib/helpdesk_web/controllers/page_html.ex
* creating helpdesk/lib/helpdesk_web/controllers/page_html/home.html.heex
* creating helpdesk/test/helpdesk_web/controllers/page_controller_test.exs
* creating helpdesk/lib/helpdesk_web/components/layouts/root.html.heex
* creating helpdesk/lib/helpdesk_web/components/layouts/app.html.heex
* creating helpdesk/lib/helpdesk_web/components/layouts.ex
* creating helpdesk/priv/static/images/logo.svg
* creating helpdesk/lib/helpdesk/mailer.ex
* creating helpdesk/lib/helpdesk_web/gettext.ex
* creating helpdesk/priv/gettext/en/LC_MESSAGES/errors.po
* creating helpdesk/priv/gettext/errors.pot
* creating helpdesk/priv/static/robots.txt
* creating helpdesk/priv/static/favicon.ico
* creating helpdesk/assets/js/app.js
* creating helpdesk/assets/vendor/topbar.js
* creating helpdesk/assets/css/app.css
* creating helpdesk/assets/tailwind.config.js

Fetch and install dependencies? [Yn]
* running mix deps.get
* running mix assets.setup
* running mix deps.compile

We are almost there! The following steps are missing:

    $ cd helpdesk
Then configure your database in config/dev.exs and run:

    $ mix ecto.create

Start your Phoenix app with:

    $ mix phx.server


    $ iex -S mix phx.server

==> phoenix_live_view
Compiling 39 files (.ex)
Generated phoenix_live_view app
===> Analyzing applications...
===> Compiling telemetry
===> Compiling telemetry_poller
==> helpdesk
Compiling 15 files (.ex)
warning: defining a Gettext backend by calling

    use Gettext, otp_app: ...

is deprecated. To define a backend, call:

    use Gettext.Backend, otp_app: :my_app

Then, instead of importing your backend, call this in your module:

    use Gettext, backend: MyApp.Gettext

  lib/helpdesk_web/gettext.ex:23: HelpdeskWeb.Gettext (module)

Generated helpdesk app
** (ErlangError) Erlang error: :enoent
    (elixir 1.17.3) lib/system.ex:1114: System.cmd("which", ["git"], [])
    (igniter 0.3.57) lib/igniter.ex:904: Igniter.prompt_on_git_changes/2
    (igniter 0.3.57) lib/igniter.ex:627: Igniter.apply_and_fetch_dependencies/2
    (igniter 0.3.57) lib/igniter/util/info.ex:46: Igniter.Util.Info.compose_install_and_validate!/6
    (igniter 0.3.57) lib/igniter/util/install.ex:77: Igniter.Util.Install.install/4
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    lib/mix/tasks/igniter.new.ex:178: Mix.Tasks.Igniter.New.run/1
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
```

**Expected behavior**
Use `where` on Windows or documentation to install `which` with `scoop install which`.

\*\* Runtime

- Elixir version 1.17.3
- Erlang version 27.1
- OS Windows 10
- Igniter version 0.4.2

**Comment by zachdaniel** [comment]
Whoops! Thank you for pointing this out. It is fixed in `0.3.58`
